import { createRequire } from "node:module";
const { chromium } = createRequire(import.meta.url)("playwright");
const BASE = "http://localhost:3000";
const OUT = "./shots";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, locale: "fr-FR" });
const page = await ctx.newPage();
const shot = async (name, full = false) => { await page.waitForTimeout(350); await page.screenshot({ path: `${OUT}/${name}.png`, fullPage: full }); console.log("capture", name); };

await page.goto(`${BASE}/`); await page.waitForLoadState("load"); await shot("accueil"); await shot("accueil-full", true);
await page.goto(`${BASE}/matchs`); await page.waitForLoadState("load"); await page.waitForTimeout(800); await shot("matchs"); await shot("matchs-full", true);
await page.goto(`${BASE}/connexion?next=%2Fanalyser`); await shot("connexion");
await page.fill('input[name="email"]', `video-${Date.now()}@exemple.fr`);
await page.fill('input[name="password"]', "motdepasse-solide");
await page.check('input[name="terms"]');
await page.getByRole("button", { name: /continuer/i }).click();
await page.waitForURL(/\/analyser$/); await page.waitForTimeout(800); await shot("analyser"); await shot("analyser-full", true);
await page.fill('input[name="q"]', "Lakers vs Celtics"); await shot("analyser-saisie");
await page.getByRole("button", { name: "Analyser", exact: true }).click();
await page.waitForSelector("text=Analyse en cours", { timeout: 20000 });
const t0 = Date.now();
await page.waitForTimeout(450); await page.screenshot({ path: `${OUT}/progress-1.png` });
await page.waitForTimeout(Math.max(0, 2000 - (Date.now() - t0))); await page.screenshot({ path: `${OUT}/progress-2.png` });
await page.waitForTimeout(Math.max(0, 3750 - (Date.now() - t0))); await page.screenshot({ path: `${OUT}/progress-3.png` });
console.log("captures progress");
await page.waitForSelector("text=Analyse prête", { timeout: 20000 }); await shot("floute"); await shot("floute-full", true);
const id = page.url().match(/ana_[a-f0-9]+/)[0];
await page.goto(`${BASE}/offres?analyse=${id}`); await page.waitForLoadState("load"); await page.waitForTimeout(600); await shot("offres"); await shot("offres-full", true);
await page.goto(`${BASE}/paiement/demo?plan=pro&analyse=${id}`); await page.waitForLoadState("load"); await shot("paiement");
await page.getByRole("button", { name: /payer/i }).click();
await page.waitForURL(/paiement=ok/); await page.waitForSelector("text=Résumé rédigé par l'IA", { timeout: 20000 }); await page.waitForTimeout(500);
await shot("resultat"); await shot("resultat-full", true);
await page.goto(`${BASE}/compte`); await page.waitForLoadState("load"); await page.waitForTimeout(500); await shot("compte");
await browser.close();
