import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
const { chromium } = createRequire(import.meta.url)("playwright");
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, locale: "fr-FR" });
const page = await ctx.newPage();
const tops = async (sel) => page.evaluate((s) => Array.from(document.querySelectorAll(s)).map((el) => ({ text: (el.textContent || "").trim().slice(0, 40), y: Math.round(el.getBoundingClientRect().top + scrollY), x: Math.round(el.getBoundingClientRect().left), w: Math.round(el.getBoundingClientRect().width), h: Math.round(el.getBoundingClientRect().height) })), sel);
const out = {};
await page.goto(`${BASE}/matchs`); await page.waitForLoadState("load"); await page.waitForTimeout(600);
out.matchs = { analyser: (await tops("article form button")).slice(0, 4), articles: (await tops("article")).slice(0, 4) };
await page.goto(`${BASE}/connexion?next=%2Fanalyser`);
await page.fill('input[name="email"]', `mesure-${Date.now()}@exemple.fr`); await page.fill('input[name="password"]', "motdepasse-solide"); await page.check('input[name="terms"]');
await page.getByRole("button", { name: /continuer/i }).click(); await page.waitForURL(/\/analyser$/);
await page.fill('input[name="q"]', "Lakers vs Celtics"); await page.getByRole("button", { name: "Analyser", exact: true }).click();
await page.waitForSelector("text=Analyse prête", { timeout: 20000 });
const id = page.url().match(/ana_[a-f0-9]+/)[0];
await page.goto(`${BASE}/offres?analyse=${id}`); await page.waitForLoadState("load"); await page.waitForTimeout(500);
out.offres = { cartes: await tops("article"), h2: await tops("article h2") };
await page.goto(`${BASE}/paiement/demo?plan=pro&analyse=${id}`); await page.getByRole("button", { name: /payer/i }).click();
await page.waitForURL(/paiement=ok/); await page.waitForSelector("text=Résumé rédigé par l'IA", { timeout: 20000 }); await page.waitForTimeout(500);
out.resultat = { h2: await tops("main h2"), cartes: (await tops("main > div > div.rounded-card, main .rounded-card")).slice(0, 12), pct: await tops("main .text-5xl") };
writeFileSync(process.argv[2], JSON.stringify(out, null, 1));
console.log(JSON.stringify(out));
await browser.close();
